INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('nick', '{noop}1234', 'USER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('admin', '{noop}admin123', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('john', '{noop}pass123', 'USER');